export const data=[
    {
        id:1,
        img:'/images/jan.png'
    },
    {
        id:2,
        img:'/images/feb.png'
    },
    {
        id:3,
        img:'/images/mar.png'
    },
    {
        id:4,
        img:'/images/apr.png'
    },
    {
        id:5,
        img:'/images/may.png'
    },
    {
        id:6,
        img:'/images/jun.png'
    },
    {
        id:7,
        img:'/images/jul.png'
    },
    {
        id:8,
        img:'/images/aug.png'
    },
    {
        id:9,
        img:'/images/sep.png'
    },
    {
        id:10,
        img:'/images/oct.png'
    },
    {
        id:11,
        img:'/images/nov.png'
    },
    {
        id:12,
        img:'/images/dec.png'
    },
]